### ISSUE TITLE
Add aiming criteria to kinesthetic target and response.

### ISSUE THREAD

**Issue by frenchjam** [PsyPhy/GRASPonISS#14]
Right now we only show the laser pointer but do not require the pointer to be on the target in order to proceed.

**Comment by frenchjam** [comment]
Currently the hand has to be raised, but I don't remember if the dot has to be on the target. I'm not sure that we want to insist. Should check with Michele.

**Comment by MicheleTagliabue** [comment]
No, I don’t think we should constraint the laser pointer to be in the target. It seems to me an unnecessary additional constraint. If they are around the center of the tunnel this is good enough for me. However, it is true that put a rough constraint on the head pitch and yaw (or the laser pointer position) could avoid involuntary responses (pressing by mistake the mouse button).

Michele Tagliabue, PhD
Centre de Neurophysique, Physiologie et Pathologie (CNPP) - UMR 8119
Institut des Neurosciences et de la Cognition
Université Paris Descartes
45 rue des Saints Pères
75270 Paris Cedex 06, France

Phone:	+33 (0)1 4286 3315
Fax:	+33 (0)1 4286 2080

michele.tagliabue@parisdescartes.fr

Personal web-page

❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏❏
